name: Deploy Docker image to Azure Windows VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      #- name: Build Docker image
      #  run: |
      #    docker build -t karizma .
      #    docker save -o karizma.tar karizma

      #- name: Transfer Docker image to Azure Windows VM
      #  run: |
      #    sudo apt-get install -y sshpass
      #    sshpass -p ${{ secrets.WINDOWS_VM_PASSWORD }} scp -P ${{ secrets.WINDOWS_VM_PORT }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null karizma.tar ${{ secrets.WINDOWS_VM_USERNAME }}@${{ secrets.WINDOWS_VM_HOST }}:'C:\Users\comet\Desktop\'

      - name: Check if container is already running
        uses: appleboy/ssh-action@master
        id: check-container
        with:
          host: ${{ secrets.WINDOWS_VM_HOST }}
          username: ${{ secrets.WINDOWS_VM_USERNAME }}
          password: ${{ secrets.WINDOWS_VM_PASSWORD }}
          port: ${{ secrets.WINDOWS_VM_PORT }}
          script: |
            docker ps -q --filter name=karizma

      - name: Stop and remove existing container (if present)
        uses: appleboy/ssh-action@master
        if: ${{ steps.check-container.outputs.stdout == 994f6b38514d }}
        with:
          host: ${{ secrets.WINDOWS_VM_HOST }}
          username: ${{ secrets.WINDOWS_VM_USERNAME }}
          password: ${{ secrets.WINDOWS_VM_PASSWORD }}
          port: ${{ secrets.WINDOWS_VM_PORT }}
          script: |
            docker stop karizma && docker rm karizma


      - name: Load new Docker image and run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WINDOWS_VM_HOST }}
          username: ${{ secrets.WINDOWS_VM_USERNAME }}
          password: ${{ secrets.WINDOWS_VM_PASSWORD }}
          port: ${{ secrets.WINDOWS_VM_PORT }}
          script: |
            docker load -i C:\Users\comet\Desktop\karizma.tar && docker run -d -p 8066:80 --name karizma karizma
