
name: Deploy Docker image to Azure Windows VM
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t karizma .
          docker save -o karizma.tar karizma
      - name: Transfer Docker image to Azure Windows VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WINDOWS_VM_HOST }}
          username: ${{ secrets.WINDOWS_VM_USERNAME }}
          password: ${{ secrets.WINDOWS_VM_PASSWORD }}
          script: |
            mkdir -p /tmp/karizma
            mv karizma.tar /tmp/karizma/

            sshpass -p 'haseeb@44271' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /tmp/karizma/karizma.tar haseeb@74.235.89.69:/C/Users/haseeb/Desktop/
      - name: Execute commands on Azure Windows VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WINDOWS_VM_HOST }}
          username: ${{ secrets.WINDOWS_VM_USERNAME }}
          password: ${{ secrets.WINDOWS_VM_PASSWORD }}
          script: |
            ssh ${{ secrets.WINDOWS_VM_USERNAME }}@${{ secrets.WINDOWS_VM_HOST }} 'cd C:/Users/haseeb/Desktop; docker load -i karizma.tar; docker run -d -p 8080:80 karizma'
