name: Deploy Docker image to Azure Windows VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t karizma .
          docker save -o karizma.tar karizma

      - name: Transfer Docker image to Azure Windows VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WINDOWS_VM_HOST }}
          username: ${{ secrets.WINDOWS_VM_USERNAME }}
          password: ${{ secrets.WINDOWS_VM_PASSWORD }}
          port: ${{ secrets.WINDOWS_VM_PORT }}
          script: |
            scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null karizma.tar ${{ secrets.WINDOWS_VM_USERNAME }}@${{ secrets.WINDOWS_VM_HOST }}:'C:\Users\comet\Desktop'

      - name: Stop and remove previous container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WINDOWS_VM_HOST }}
          username: ${{ secrets.WINDOWS_VM_USERNAME }}
          password: ${{ secrets.WINDOWS_VM_PASSWORD }}
          port: ${{ secrets.WINDOWS_VM_PORT }}
          script: |
            ssh ${{ secrets.WINDOWS_VM_USERNAME }}@${{ secrets.WINDOWS_VM_HOST }} 'docker stop karizma && docker rm karizma || true'

      - name: Load new Docker image and run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WINDOWS_VM_HOST }}
          username: ${{ secrets.WINDOWS_VM_USERNAME }}
          password: ${{ secrets.WINDOWS_VM_PASSWORD }}
          port: ${{ secrets.WINDOWS_VM_PORT }}
          script: |
            ssh ${{ secrets.WINDOWS_VM_USERNAME }}@${{ secrets.WINDOWS_VM_HOST }} 'docker load -i C:\Users\comet\Desktop\karizma.tar && docker run -d -p 8066:80 --name karizma karizma'
