name: Deploy Docker image to Azure Windows VM
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t karizma .
          docker save -o karizma.tar karizma

      - name: Transfer Docker image to Azure Windows VM
        uses: appleboy/sftp-upload-action@master
        with:
          host: ${{ secrets.WINDOWS_VM_HOST }}
          username: ${{ secrets.WINDOWS_VM_USERNAME }}
          password: ${{ secrets.WINDOWS_VM_PASSWORD }}
          local_path: ./karizma.tar
          remote_path: 'C:\Users\haseeb\Desktop\karizma.tar'

      - name: Execute commands on Azure Windows VM
        uses: appleboy/winrm-action@master
        with:
          host: ${{ secrets.WINDOWS_VM_HOST }}
          port: 5986
          username: ${{ secrets.WINDOWS_VM_USERNAME }}
          password: ${{ secrets.WINDOWS_VM_PASSWORD }}
          script: |
            cd C:\Users\haseeb\Desktop
            docker load -i karizma.tar
            docker run -d -p 8080:80 karizma

